name-template: 'v$NEXT_MAJOR_VERSION'
tag-template: 'v$NEXT_MAJOR_VERSION'
version-template: '$MAJOR'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug fixes'
    labels:
      - 'bug'
  - title: '🧰 Technical changes'
    label: 'technical change'
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## 🔖 concrexit v$NEXT_MAJOR_VERSION

  $CHANGES

