variables:
  POSTGRES_DB: thalia
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  CI_DEPS: psycopg2
  # https://hub.docker.com/r/twiggers/python-thalia/
  # https://github.com/thomwiggers/python-thalia
  # Should get auto-updated with the official 'python' repository
  # Installs:
  #  - pip: tox, coverage
  #  - apt: ghostscript
  PY35_IMAGE: twiggers/python-thalia:3.5

pep8:
  image: $PY35_IMAGE
  before_script:
    - export PIP_CACHE_DIR="pip-cache"
  script:
    - tox -e flake8

.djangotest: &djangotest
  services:
    - postgres:latest
  before_script:
    - export PIP_CACHE_DIR="pip-cache"
    - mkdir -p pip-cache
    - git log -1
  script:
    - tox -e ${PYTHON_VERSION}-${DJANGO_VERSION}
    - cd website
    - coverage report

python35-django11:
  <<: *djangotest
  image: $PY35_IMAGE
  variables:
    PYTHON_VERSION: py35
    DJANGO_VERSION: django11

docs:
  image: $PY35_IMAGE
  before_script:
    # install django deps
    - pip install -r requirements.txt
    - cd docs
    # install doc deps
    - pip install -r requirements.txt
  script:
    - env -u GITLAB_CI make doctest
    - test -z "$(env -u GITLAB_CI make html | egrep -w 'SEVERE:|ERROR:')"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - pip-cache

# vim: set sw=2 ts=2 et :
