variables:
  POSTGRES_DB: thalia
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  CI_DEPS: psycopg2-binary
  # https://hub.docker.com/r/twiggers/python-thalia/
  # https://github.com/thomwiggers/python-thalia
  # Should get auto-updated with the official 'python' repository
  # Installs:
  #  - pip: tox, coverage
  #  - apt: ghostscript
  PY35_IMAGE: thalia/python-thalia:3.5
  PY36_IMAGE: thalia/python-thalia:3.6
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"

pep8:
  image: $PY35_IMAGE
  before_script:
  script:
    - tox -e flake8

.djangotest: &djangotest
  services:
    - postgres:latest
  before_script:
    - git log -1
  script:
    - tox -e ${PYTHON_VERSION}-${DJANGO_VERSION}
    - cd website
    - coverage report

python35-django20:
  <<: *djangotest
  image: $PY35_IMAGE
  variables:
    PYTHON_VERSION: py35
    DJANGO_VERSION: django20

python36-django20:
  <<: *djangotest
  image: $PY36_IMAGE
  variables:
    PYTHON_VERSION: py36
    DJANGO_VERSION: django20

docs:
  image: $PY35_IMAGE
  before_script:
    # install django deps
    - pip install -r requirements.txt
    - cd docs
    # install doc deps
    - pip install -r requirements.txt
  script:
    - echo "Building current docs"
    - env -u GITLAB_CI make doctest
    - env -u GITLAB_CI sphinx-build -M html "." "_build" -W
    - echo "Checking if there are changes"
    - ./generate-apidocs.sh
    - git diff --exit-code

cache:
  key: "$CI_JOB_NAME"
  paths:
    - "${PIP_CACHE_DIR}"

# vim: set sw=2 ts=2 et :
