variables:
  POSTGRES_DB: thalia
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  # https://hub.docker.com/r/thalia/python-thalia/
  # https://github.com/thaliawww/python-thalia
  # Should get auto-updated with the official 'python' repository
  # Installs:
  #  - pip: coverage, poetry
  #  - apt: ghostscript
  PY37_IMAGE: thalia/python-thalia:3.7
  PY38_IMAGE: thalia/python-thalia:3.8
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/pip-cache"

stages:
  - test
  - deploy

codestyle:
  stage: test
  image: $PY37_IMAGE
  before_script:
    - poetry install --no-interaction
  script:
    - black --check .
    # Check for obsolete translations in .po files (starting with `#~`).
    - cd website
    - grep --include="*.po" --files-with-matches --recursive "^#~" && exit 1 || echo "No obsolete translations found."
    # Check for untranslated strings in .po files
    - empty_strings=$(sed '$a\\' **/locale/nl/LC_MESSAGES/django.po | tac | sed '/^$/N;/\nmsgstr ""$/,/^msgid/!d' | tac)
    - empty_strings+=$(sed '$a\\' locale/nl/LC_MESSAGES/django.po | tac | sed '/^$/N;/\nmsgstr ""$/,/^msgid/!d' | tac)
    - if [[ $empty_strings ]]; then echo $empty_strings && exit 1; else echo "No untranslated strings found."; fi
    # Check for fuzzy translations in .po files
    - grep --include="*.po" --files-with-matches --recursive "#, fuzzy" && exit 1 || echo "No fuzzy translations found."

.djangotest: &djangotest
  stage: test
  services:
    - postgres:latest
  before_script:
    - git log -1
    - poetry install --no-interaction
  script:
    - cd website
    - poetry run python manage.py check
    - poetry run python manage.py templatecheck --project-only
    - poetry run python manage.py makemigrations --no-input --check --dry-run
    - poetry run python -Wall -mcoverage run manage.py test
    - coverage report --fail-under=100 --omit registrations/urls.py registrations/**.py
    - coverage report --fail-under=100 --omit payments/urls.py payments/**.py
    - coverage report

python37-django22:
  <<: *djangotest
  image: $PY37_IMAGE
  after_script:
    - cd website
    - coverage html --directory=covhtml --title="${CI_COMMIT_REF_SLUG} Coverage Report"
  artifacts:
    paths:
      - website/covhtml/

python38-django22:
  <<: *djangotest
  image: $PY38_IMAGE
  allow_failure: true

.sshsetup: &sshsetup
  before_script:
    - mkdir -p ~/.ssh
    - echo "$IVO_KNOWN_HOST" > ~/.ssh/known_hosts
    - echo "$COVERAGE_DEPLOY_SSH_KEY" > ~/.ssh/id_coverage
    - echo "$DOCS_DEPLOY_SSH_KEY" > ~/.ssh/id_docs
    - chmod 0600 ~/.ssh/id_*
    - apt-get update
    - apt-get install -y openssh-client

coverage deploy:
  stage: deploy
  image: debian:stretch
  dependencies:
    - python37-django22
  environment:
    name: coverage/${CI_COMMIT_REF_NAME}
    url: https://coverage.technicie.nl/${CI_COMMIT_REF_SLUG}/
    on_stop: coverage remove
  <<: *sshsetup
  script:
    - |
      sftp -i ~/.ssh/id_coverage coveragewww@ivo.thalia.nu -b <<EOF
      -rm ${CI_COMMIT_REF_SLUG}/*
      -rmdir ${CI_COMMIT_REF_SLUG}
      put -r website/covhtml ${CI_COMMIT_REF_SLUG}
      EOF

coverage remove:
    stage: deploy
    when: manual
    image: debian:stretch
    environment:
        name: coverage/${CI_COMMIT_REF_NAME}
        action: stop
    variables:
        GIT_STRATEGY: none
    <<: *sshsetup
    script:
      - |
        sftp -i ~/.ssh/id_coverage coveragewww@ivo.thalia.nu -b <<EOF
        rm ${CI_COMMIT_REF_SLUG}/*
        rmdir ${CI_COMMIT_REF_SLUG}
        EOF

docs tests:
  stage: test
  image: $PY37_IMAGE
  before_script:
    # install django deps
    - poetry install --no-interaction --extras "docs"
  script:
    - echo "Building current docs"
    - cd docs
    - env -u GITLAB_CI poetry run make doctest
    - env -u GITLAB_CI poetry run sphinx-build -W . _build
    - echo "Checking if there are changes"
    - poetry run ./generate-apidocs.sh
    - git diff --exit-code
  artifacts:
    paths:
      - docs/_build

docs deploy:
  stage: deploy
  image: debian:stretch
  dependencies:
    - docs tests
  environment:
    name: docs/${CI_COMMIT_REF_NAME}
    url: https://docs.technicie.nl/${CI_COMMIT_REF_SLUG}/
    on_stop: docs remove
  <<: *sshsetup
  script:
    - |
      sftp -i ~/.ssh/id_docs docswww@ivo.thalia.nu -b <<EOF
      -rm ${CI_COMMIT_REF_SLUG}/*/*
      -rm ${CI_COMMIT_REF_SLUG}/*
      -rmdir ${CI_COMMIT_REF_SLUG}/_images
      -rmdir ${CI_COMMIT_REF_SLUG}/_modules
      -rmdir ${CI_COMMIT_REF_SLUG}/_sources
      -rmdir ${CI_COMMIT_REF_SLUG}/_static
      -rmdir ${CI_COMMIT_REF_SLUG}/doctest
      -rmdir ${CI_COMMIT_REF_SLUG}/doctrees
      -rmdir ${CI_COMMIT_REF_SLUG}
      -mkdir ${CI_COMMIT_REF_SLUG}
      put -r docs/_build/* ${CI_COMMIT_REF_SLUG}
      EOF

docs remove:
  stage: deploy
  when: manual
  image: debian:stretch
  environment:
    name: docs/${CI_COMMIT_REF_NAME}
    action: stop
  variables:
    GIT_STRATEGY: none
  <<: *sshsetup
  script:
    - |
      sftp -i ~/.ssh/id_docs docswww@ivo.thalia.nu -b <<EOF
      rm ${CI_COMMIT_REF_SLUG}/*/*
      rm ${CI_COMMIT_REF_SLUG}/*
      rmdir ${CI_COMMIT_REF_SLUG}/_images
      rmdir ${CI_COMMIT_REF_SLUG}/_modules
      rmdir ${CI_COMMIT_REF_SLUG}/_sources
      rmdir ${CI_COMMIT_REF_SLUG}/_static
      rmdir ${CI_COMMIT_REF_SLUG}/doctest
      rmdir ${CI_COMMIT_REF_SLUG}/doctrees
      rmdir ${CI_COMMIT_REF_SLUG}
      EOF

build docker image:
  stage: test
  services:
    - docker:dind
  image: thalia/docker-compose
  tags:
    - docker
  except:
    - tags
  before_script:
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username thaliawww --password-stdin registry.hub.docker.com
  script:
    - docker-compose config -q
    - docker-compose build --build-arg install_dev_requirements=$DEV_REQUIREMENTS --build-arg source_commit=$(git rev-parse HEAD) web
    - docker tag $DOCKER_LATEST $DOCKER_TAG
    - docker push $DOCKER_TAG
  variables:
    DEV_REQUIREMENTS: 1
    DOCKER_LATEST: registry.hub.docker.com/thalia/concrexit:latest
    DOCKER_TAG: registry.hub.docker.com/thalia/concrexit:$CI_COMMIT_SHA

build production docker image:
  extends: build docker image
  only:
    - tags
  except:
    - master
  after_script:
    - docker tag $DOCKER_TAG $DOCKER_TAG_PRODUCTION
    - docker tag $DOCKER_TAG $DOCKER_LATEST
    - docker push $DOCKER_TAG_PRODUCTION
    - docker push $DOCKER_LATEST    
  variables:
    DOCKER_TAG_PRODUCTION: registry.hub.docker.com/thalia/concrexit:$CI_COMMIT_TAG
    DEV_REQUIREMENTS: 0

.reviewsetup:
  when: "manual"
  image: "python:latest"
  variables:
      AWS_DEFAULT_REGION: "eu-west-1"
  before_script:
    - "DEBIAN_FRONTEND=noninteractive apt-get --yes --quiet update"
    - "DEBIAN_FRONTEND=noninteractive apt-get --yes --quiet install jq"
    - "pip install awscli"

review create:
  extends: ".reviewsetup"
  stage: "deploy"
  environment:
    name: "review/${CI_COMMIT_REF_NAME}"
    url: "https://${CI_COMMIT_REF_SLUG}.public.review.technicie.nl/"
    on_stop: "review remove"
  script:
    - "username=$(head /dev/urandom | tr -dc 'a-z' | head -c 10)"
    - "password=$(head /dev/urandom | tr -dc 'a-zA-Z' | head -c 32)"
    - >-
      sed --in-place
      --expression "s/@version@/$CI_COMMIT_SHA/g"
      --expression "s/@username@/$username/g"
      --expression "s/@password@/$password/g"
      ./resources/ec2-bootstrap.sh
    - "resources/review-host-create.sh"
    - 'echo -e "The deployment is done. Please wait for the website to come up. You can login on https://${CI_COMMIT_REF_SLUG}.public.review.technicie.nl/ with:\nUsername:$username\nPassword:$password"'


review remove:
  extends: ".reviewsetup"
  stage: "deploy"
  environment:
    name: "review/${CI_COMMIT_REF_NAME}"
    action: "stop"
  script:
    - "resources/review-host-remove.sh"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - "${PIP_CACHE_DIR}"
