variables:
  POSTGRES_DB: thalia
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  CI_DEPS: psycopg2

pep8:
  image: python:3.5
  before_script:
    - export PIP_CACHE_DIR="pip-cache"
    - pip install tox
  script:
    - tox -e flake8

.djangotest: &djangotest
  services:
    - postgres:latest
  before_script:
    - export PIP_CACHE_DIR="pip-cache"
    - mkdir -p pip-cache
    - git log -1
    - pip install tox coverage
    - apt-get update
    - apt-get install -y ghostscript  # required for Thabloid's tests
  script:
    - tox -e ${PYTHON_VERSION}-${DJANGO_VERSION}
    - cd website
    - coverage report

python35-django11:
  <<: *djangotest
  image: python:3.5
  variables:
    PYTHON_VERSION: py35
    DJANGO_VERSION: django11

python35-django20:
  <<: *djangotest
  image: python:3.5
  variables:
    PYTHON_VERSION: py35
    DJANGO_VERSION: django20

python36-django20:
  <<: *djangotest
  image: python:3.6
  variables:
    PYTHON_VERSION: py36
    DJANGO_VERSION: django20

docs:
  image: python:3.5
  before_script:
    # install django deps
    - pip install -r requirements.txt
    - cd docs
    # install doc deps
    - pip install -r requirements.txt
  script:
    - env -u GITLAB_CI make doctest
    - test -z "$(env -u GITLAB_CI make html | egrep -w 'SEVERE:|ERROR:')"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - pip-cache

# vim: set sw=2 ts=2 et :
