---

version: '3.5'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        environment:
            DHPARAM_GENERATION: "false"
            DHPARAM_BITS: 2048
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /tmp/certs/:/etc/nginx/certs/

    web:
        image: docker.pkg.github.com/svthalia/concrexit/commit:2a00a9be4b558c5d5877320e3046f89fe1fd9c34
        entrypoint: /bin/bash
        depends_on:
            - nginx-proxy
        ports:
            - 127.0.0.1:8000:8000
        command: >-
          -c "python manage.py migrate
          && python manage.py createreviewuser --username user --password pass
          && python manage.py createfixtures -a
          && python manage.py runserver 0.0.0.0:8000"
        environment:
            VIRTUAL_HOST: "test.local"
