.build-docker-image-setup:
  stage: test
  tags:
    - docker
  image: docker
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "thaliawww" --password-stdin "registry.hub.docker.com"
  variables:
    DOCKER_LATEST: registry.hub.docker.com/thalia/concrexit:latest
    DOCKER_TAG: registry.hub.docker.com/thalia/concrexit:${CI_COMMIT_SHA}
    DOCKER_DEPENDENCIES_LATEST: registry.hub.docker.com/thalia/concrexit-dependencies:latest
    DOCKER_TAG_PRODUCTION: registry.hub.docker.com/thalia/concrexit:${CI_COMMIT_TAG}

schedule:build-docker-image-dependencies:
  extends: .build-docker-image-setup
  only:
    - schedules
  script:
    - docker build --file "Dockerfile.dependencies" --quiet --build-arg "install_dev_requirements=1" --tag "${DOCKER_DEPENDENCIES_LATEST}" .
    - docker push "${DOCKER_DEPENDENCIES_LATEST}"

build-docker-image:
  extends: .build-docker-image-setup
  except:
    - /v[\d\.]+/
    - schedules
  script:
    - docker build --quiet --build-arg "source_commit=${CI_COMMIT_SHA}" --tag "${DOCKER_LATEST}" .
    - docker tag "${DOCKER_LATEST}" "${DOCKER_TAG}"
    - docker push "${DOCKER_TAG}"

build-docker-image-production:
  extends: .build-docker-image-setup
  only:
    - /v[\d\.]+/
  script:
    - docker build --file "Dockerfile.dependencies" --quiet --build-arg "install_dev_requirements=0" --tag "${DOCKER_DEPENDENCIES_LATEST}" .
    - docker build --quiet --build-arg "source_commit=${CI_COMMIT_SHA}" --tag "${DOCKER_LATEST}" .
    - docker tag "${DOCKER_LATEST}" "${DOCKER_TAG_PRODUCTION}"
    - docker push "${DOCKER_TAG_PRODUCTION}"
    - docker push "${DOCKER_LATEST}"
