---

coverage-deploy:
  stage: deploy
  except:
    - schedules
  dependencies:
    - django-tests
  environment:
    name: coverage/${CI_COMMIT_REF_NAME}
    url: https://s3-eu-west-1.amazonaws.com/thalia-coverage/${CI_COMMIT_REF_SLUG}/index.html
  image: python:latest
  before_script:
      - pip install awscli
  script:
    - aws s3 sync --only-show-errors "covhtml" "s3://thalia-coverage/${CI_COMMIT_REF_SLUG}/"

docs-deploy:
  stage: deploy
  except:
    - schedules
  dependencies:
    - docs-tests
  environment:
    name: documentation/${CI_COMMIT_REF_NAME}
    url: https://s3-eu-west-1.amazonaws.com/thalia-documentation/${CI_COMMIT_REF_SLUG}/index.html
  image: python:latest
  before_script:
      - pip install awscli
  script:
    - aws s3 sync --only-show-errors "docs/_build" "s3://thalia-documentation/${CI_COMMIT_REF_SLUG}/"
