---

name: Review Environments

on:
  issue_comment:
    types: [created, edited]

jobs:
    create:
        name: Deploy review environment
        runs-on: ubuntu-18.04
        if: github.event.issue.pull_request && github.event.comment.body == 'deploy review'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Get commit hash
              run: echo ::set-env name=COMMIT_SHA::$(curl --location --silent ${{ github.event.issue.pull_request.patch_url }} | head --lines 1 | cut --delimiter " " --fields 2)

            - name: Generate username
              run: echo ::set-env name=username::$(head /dev/urandom | tr -dc 'a-z' | head -c 10)

            - name: Generate password
              run: echo ::set-env name=password::$(head /dev/urandom | tr -dc 'a-zA-Z' | head -c 32)

            - name: Set variables in bootstrap script
              run: >-
                   sed --in-place
                   --expression "s/@version@/$COMMIT_SHA/g"
                   --expression "s/@username@/$username/g"
                   --expression "s/@password@/$password/g"
                   resources/continuous-integration/review/ec2-bootstrap.sh

            - name: Run script to create review environment
              run: resources/continuous-integration/review/review-host-create.sh

            - uses: peter-evans/create-or-update-comment@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  issue-number: ${{ github.event.issue.number }}
                  body: |
                      The review environment deployment is done. Please wait for the website to come up.
                      You can login on [${{ env.COMMIT_SHA }}.public.review.technicie.nl](https://${{ env.COMMIT_SHA }}.public.review.technicie.nl/) with:
                      Username: ${{ env.username }}
                      Password: ${{ env.password }}

    remove:
        name: Remove review environment
        runs-on: ubuntu-18.04
        if: github.event.issue.pull_request && github.event.comment.body == 'remove review'
        steps:
            - name: Get commit hash
              run: echo ::set-env name=COMMIT_SHA::$(curl --location --silent ${{ github.event.issue.pull_request.patch_url }} | head --lines 1 | cut --delimiter " " --fields 2)

            - name: Run script to remove review environment
              run: resources/continuous-integration/review/review-host-remove.sh
