---

name: Linting and Testing
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  codestyle:
    name: Codestyle
    runs-on: ubuntu-18.04
    container: thalia/concrexit-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run black
        run: make blackcheck

  linting:
    name: Linting
    runs-on: ubuntu-18.04
    container: thalia/concrexit-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run pylint
        run: make pylint

  docstyle:
    name: Docstring style
    runs-on: ubuntu-18.04
    container: thalia/concrexit-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run pydocstyle
        run: make pydocstyle

  tests:
    name: Django Tests
    runs-on: ubuntu-18.04
    container: thalia/concrexit-dependencies
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: thalia
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      DJANGO_ENV: testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

      - name: Report coverage
        run: make coverage

      - name: Create coverage report
        run: make covhtml

      - name: Save coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-html
          path: covhtml

  documentation-tests:
    name: Documentation Tests
    runs-on: ubuntu-18.04
    container: thalia/concrexit-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run doctest
        run: make doctest

      - name: Run Sphinx
        run: make docs

      - name: Run API docs script
        run: |
          make apidocscheck

      - name: Save documentation HTML
        uses: actions/upload-artifact@v2
        with:
          name: docs-html
          path: docs/_build
